In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
print(a)
print (b)

In [2]:
b[1]=4


In [3]:
b

array([1, 4, 3])

In [4]:
a[2]=5
a

array([1, 2, 5])

In [11]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [12]:
c[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
c[:0]

array([], shape=(0, 3), dtype=int32)

In [14]:
c[:1]

array([[1, 2, 3]])

In [15]:
c[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a[0]

1

In [17]:
a[1]

2

In [18]:
a[2]

5

# Numpy array  initialisation


In [22]:
a=np.zeros([3,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
a=np.arange(10,25,5)

In [26]:
print(a)

[10 15 20]


# np.linspace(startnum,endnum,numberofplots)

In [30]:
b=np.linspace(5,6,10)
print (b)

[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ]


# how to create array with same number

In [31]:
c=np.full([3,4],5)

In [32]:
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


# Random array

In [33]:
d=np.random.random([3,4])

In [34]:
print (d)

[[0.50468462 0.94319417 0.00687731 0.71479226]
 [0.10273678 0.28018889 0.93618812 0.1996057 ]
 [0.83872966 0.06981104 0.73040514 0.50422279]]


# How do we acess what is wrong with array

In [35]:
e=np.array([[1,2,3],[4,5,6]])

In [36]:
print(e)

[[1 2 3]
 [4 5 6]]


# np.array.shapen return tuple (rownum,columnum)

In [37]:
print(e.shape)

(2, 3)


In [39]:
e.shape=(3,2)

In [41]:
print(e.shape[0])

3


In [42]:
print(e)

[[1 2]
 [3 4]
 [5 6]]


In [43]:
print(e.shape[1])

2


In [44]:
print(e)

[[1 2]
 [3 4]
 [5 6]]


# How to get total number of columns
np.arange(points needeed)

In [45]:
a=np.arange(24)

In [46]:
a.size

24

In [47]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


# ndim gives the number of the dimensions

In [50]:
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a.shape[0])
print(a)

3
[[1 2]
 [3 4]
 [5 6]]


# datatype is the type of elements in numpy

In [51]:
a.dtype

dtype('int32')

In [52]:
b=np.linspace(5,7,11)

In [53]:
b.dtype

dtype('float64')

# Numpy is used for linear algebric expression

In [54]:
import numpy as np


In [57]:
a=np.array([20,10])
np.sum(a)

30

In [68]:
b=[3,5]
np.sum(b)

8

In [69]:
np.subtract(a,b)

array([17,  5])

In [67]:
print(np.sum([a,b]))
print(np.subtract(a,b))

38
[17  5]


# columnwise sum

In [70]:
np.sum([a,b],axis=0)

array([23, 15])

# row wise sum

In [72]:
np.sum([a,b], axis=1)

array([30,  8])

In [73]:
np.exp(a)

array([4.85165195e+08, 2.20264658e+04])

In [74]:
np.sqrt(a)

array([4.47213595, 3.16227766])

In [78]:
a=4

In [79]:
np.sqrt(a)

2.0

In [80]:
np.sin(a)

-0.7568024953079282

In [82]:
np.cos(a)

-0.6536436208636119

In [83]:
np.log(a)

1.3862943611198906

# array cpmparison

In [84]:
a=[1,2,3]
b=[3,4,3]
np.equal(a,b)
print(np.equal(a,b))
print(np.array_equal(a,b))

[False False  True]
False


In [86]:
a=[1,2,3]
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.median(a))
print(np.corrcoef(a))

6
1
3
2.0
0.816496580927726
2.0
1.0


# concept of broad casting ## very impoertant in data analytics

In [91]:
a=np.array(([1,2,3],[4,5,6]))
b=np.array([3,4,5])
print(a)
print(b)
print(np.sum([a,b]))

[[1 2 3]
 [4 5 6]]
[3 4 5]
[[ 4  6  8]
 [ 7  9 11]]


In [89]:
a=np.array(([1,2,3],[4,5,6]))
b=np.array([3,4,5])
print(a)
print(b)
print(np.multiply(a,b))

[[1 2 3]
 [4 5 6]]
[3 4 5]
[[ 3  8 15]
 [12 20 30]]


In [92]:
a=np.array(([1,2,3],[4,5,6]))
b=np.array([3,4,5])
print(a)
print(b)
print(np.divide(a,b))

[[1 2 3]
 [4 5 6]]
[3 4 5]
[[0.33333333 0.5        0.6       ]
 [1.33333333 1.25       1.2       ]]


# index and slicing

In [94]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0])
print(a[:1])
print(a[:1,1:])

[1 2 3]
[[1 2 3]]
[[2 3]]


In [95]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0])
print(a[:1])
print(a[:,1:])

[1 2 3]
[[1 2 3]]
[[2 3]
 [5 6]
 [8 9]]


In [96]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0])
print(a[:1])
print(a[:2,1:])

[1 2 3]
[[1 2 3]]
[[2 3]
 [5 6]]


In [104]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[:2,2:])

[[3]
 [6]]


# array manipulation

# concatenate


# ROW WISE AND COLUMN WISE CONCATENATE

In [15]:
import numpy as np
a=np.array([[1,2,3,],[3,2,1]])
b=np.array([[7,8,9],[9,8,7]])
print("matrix A =")
print(a)
print('Matrix B =')
print (b)

print("MAtrix after concate ROW WISE= ")
print(np.concatenate([a,b],axis=0))

matrix A =
[[1 2 3]
 [3 2 1]]
Matrix B =
[[7 8 9]
 [9 8 7]]
MAtrix after concate ROW WISE= 
[[1 2 3]
 [3 2 1]
 [7 8 9]
 [9 8 7]]


In [20]:
a=np.array([[1,2,3,],[3,2,1]])
b=np.array([[7,8,9],[9,8,7]])
print("matrix A =")
print(a)
print('Matrix B =')
print (b)
print("Matrix after concatenate COLUMN WISE =")
print(np.concatenate([a,b],axis=1))

matrix A =
[[1 2 3]
 [3 2 1]]
Matrix B =
[[7 8 9]
 [9 8 7]]
Matrix after concatenate COLUMN WISE =
[[1 2 3 7 8 9]
 [3 2 1 9 8 7]]


#  STACK

In [25]:
a=np.array([[1,2,3]])
b=np.array([[7,8,9]])
print("matrix A =")
print(a)
print('Matrix B =')
print (b)
print("STACK MATRIX=")
print(np.stack([a,b],axis=0))# Row wise

matrix A =
[[1 2 3]]
Matrix B =
[[7 8 9]]
STACK MATRIX=
[[[1 2 3]]

 [[7 8 9]]]


In [29]:
print("STACK MATRIX =")
print(np.stack([a,b],axis=1))



STACK MATRIX =
[[[1 2 3]
  [7 8 9]]]


In [30]:
a=np.array([[1,2,3,],[3,2,1]])
b=np.array([[7,8,9],[9,8,7]])
print("matrix A =")
print(a)
print('Matrix B =')
print (b)
print("Matrix after stack ROW WISE =")
print(np.stack([a,b],axis=0))


matrix A =
[[1 2 3]
 [3 2 1]]
Matrix B =
[[7 8 9]
 [9 8 7]]
Matrix after stack ROW WISE =
[[[1 2 3]
  [3 2 1]]

 [[7 8 9]
  [9 8 7]]]


In [31]:
print("Matrix after stack COLUMN WISE =")
print(np.stack([a,b],axis=1))


Matrix after stack COLUMN WISE =
[[[1 2 3]
  [7 8 9]]

 [[3 2 1]
  [9 8 7]]]


In [33]:
print("Matrix after stack HORIZONTAL WISE =")
print(np.hstack([a,b]))


Matrix after stack HORIZONTAL WISE =
[[1 2 3 7 8 9]
 [3 2 1 9 8 7]]


In [35]:
print("Matrix after stack VERTICAL WISE =")
print(np.vstack([a,b]))


Matrix after stack VERTICAL WISE =
[[1 2 3]
 [3 2 1]
 [7 8 9]
 [9 8 7]]


# SPLITTING THE ARRAY

# np.split(array,index,axis)

In [37]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [39]:
print(np.split(a,2,0))

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [40]:
print(np.split(a,3,1))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [41]:
a[:1]

array([[1, 2, 3]])

In [42]:
a[1:2]

array([[4, 5, 6]])

In [43]:
a[:,2:]

array([[3],
       [6]])

In [45]:
a[:,1:2]

array([[2],
       [5]])